version: 2
sources:
  - name: RAW_DATA # Logical name for the source
    database: ANALYTICS # Optional: overrides default db
    schema: DBT_ # Schema where the source table lives
    tables:
      - name: AISLES # Actual table name in Snowflake
        description: "AISLES data from SALES"
        columns:
          - name: AISLE
            description: "ASILE_NAME"
          - name: AISLE_ID
            description: "Unique ASILE ID for each customer"
            tests:
              - not_null
              - unique
      - name: PRODUCTS
        description: "Product data from sales"
        columns:
          - name: PRODUCT_ID
            description: "Unique ID of each product"
            tests:
              - not_null
              - unique
          - name: PRODUCT_NAME
            description: "Name of the product"
            tests:
              - not_null
          - name: AISLE_ID
            description: "foreign key for Asiles table"
            tests:
              - not_null
          - name: DEPARTMENT_ID
            description: "foreign key for departments table"
            tests:
              - not_null
